### PR TITLE
Fixed relative positioning of container sometimes messing up page structure

### PR DESCRIPTION
**Pull request by gstkein**
Fixed relative positioning of container sometimes messing up page structure

### CODE REVIEW

**Comment by wesbaker** [comment]
I don't think this is a good idea. The container should be relative and the slide/element/image should be absolute and always in the top left corner of the container. If your images are being relatively positioned, then position them relatively from the container.

**Comment by gstkein** [comment]
you're right, how about wrapping the container into another container with the same positioning and size as the original one?

Also have you read about the .stop(true,true)?

**Comment by wesbaker** [comment]
> you're right, how about wrapping the container into another container with the same positioning and size as the original one?

It's hard for me to offer help without an example or a picture. Normally this plugin was used for slideshows, so that's my context here. If you have an example, I could help out a bit.

> Also have you read about the .stop(true,true)?

What do you mean?

**Comment by gstkein** [comment]
how can I send you an html example? 

I mean that there is a bug, with newer browsers, when a user switches tabs and leaves an animation running, the browser queues animation cycles to save processor power, when the user switches back the animations get super accelerated since there were so many animations queued. That can be fixed by adding .stop(true,true) previous to the fade in or fadeout.

**Comment by wesbaker** [comment]
> how can I send you an html example?

A screenshot would be better actually.

> I mean that there is a bug, with newer browsers, when a user switches tabs and leaves an animation running, the browser queues animation cycles to save processor power, when the user switches back the animations get super accelerated since there were so many animations queued. That can be fixed by adding .stop(true,true) previous to the fade in or fadeout.

Someone else sent in [a pull request for that](https://github.com/wesbaker/jquery.innerFade/pull/11), so it should be fixed now.

**Comment by gstkein** [comment]
oh, great

El 31 de octubre de 2011 17:37, Wes Baker <
reply@reply.github.com>escribi:

**Pull request closed without merging**
